export const peopleLayoutStyles = {
  page: {
    display: "flex",
    gap: 0,
    minHeight: 0,
    flex: 1,
    overflow: "hidden",
  } as const,
  sidebar: {
    width: 280,
    minWidth: 280,
    flexShrink: 0,
    borderRight: "1px solid #e2e8f0",
    display: "flex",
    flexDirection: "column" as const,
    backgroundColor: "#fafafa",
  } as const,
  sidebarHeader: {
    padding: "16px 20px",
    borderBottom: "1px solid #e2e8f0",
    backgroundColor: "#fff",
  } as const,
  sidebarTitle: { margin: 0, fontSize: "1rem", fontWeight: 600, color: "#1e293b" } as const,
  sidebarSubtitle: { margin: "4px 0 0", fontSize: "0.8125rem", color: "#64748b" } as const,
  peopleList: { flex: 1, overflowY: "auto" as const, padding: "8px 0" } as const,
  personRow: (selected: boolean) =>
    ({
      display: "flex",
      alignItems: "center",
      gap: 12,
      padding: "12px 16px",
      margin: "0 8px",
      borderRadius: 8,
      cursor: "pointer",
      border: "none",
      width: "calc(100% - 16px)",
      textAlign: "left" as const,
      backgroundColor: selected ? "#eef2ff" : "transparent",
      color: "#1e293b",
      transition: "background-color 0.15s",
    }) as const,
  avatar: {
    width: 40,
    height: 40,
    borderRadius: "50%",
    backgroundColor: "#e2e8f0",
    flexShrink: 0,
    overflow: "hidden" as const,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1rem",
    color: "#64748b",
  } as const,
  personInfo: { flex: 1, minWidth: 0 } as const,
  personName: {
    fontSize: "0.9375rem",
    fontWeight: 500,
    whiteSpace: "nowrap" as const,
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
  } as const,
  personCount: { fontSize: "0.75rem", color: "#64748b", marginTop: 2 } as const,
  menuButton: {
    padding: 4,
    borderRadius: 6,
    border: "none",
    background: "none",
    cursor: "pointer",
    color: "#64748b",
    fontSize: "1.125rem",
    lineHeight: 1,
    flexShrink: 0,
  } as const,
  dropdown: {
    position: "absolute" as const,
    right: 0,
    top: "100%",
    marginTop: 4,
    minWidth: 180,
    background: "#fff",
    borderRadius: 8,
    border: "1px solid #e2e8f0",
    boxShadow: "0 10px 15px -3px rgba(0,0,0,0.1)",
    padding: "4px 0",
    zIndex: 100,
  } as const,
  dropdownItem: {
    display: "block",
    width: "100%",
    padding: "10px 16px",
    border: "none",
    background: "none",
    textAlign: "left" as const,
    fontSize: "0.875rem",
    color: "#475569",
    cursor: "pointer",
  } as const,
};
