export const peopleStyles = {
  detail: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column" as const,
    padding: 24,
    backgroundColor: "#fff",
  } as const,
  detailEmpty: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#94a3b8",
    fontSize: "0.9375rem",
  } as const,
  detailHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
    flexWrap: "wrap" as const,
    gap: 12,
  } as const,
  detailTitle: { margin: 0, fontSize: "1.25rem", fontWeight: 600, color: "#1e293b" } as const,
  detailMeta: { fontSize: "0.875rem", color: "#64748b", marginTop: 4 } as const,
  primaryButton: {
    padding: "8px 16px",
    fontSize: "0.875rem",
    fontWeight: 500,
    borderRadius: 8,
    border: "none",
    background: "#4f46e5",
    color: "#fff",
    cursor: "pointer",
  } as const,
  secondaryButton: {
    padding: "8px 16px",
    fontSize: "0.875rem",
    fontWeight: 500,
    borderRadius: 8,
    border: "1px solid #e2e8f0",
    background: "#fff",
    color: "#475569",
    cursor: "pointer",
  } as const,
  photoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(120px, 1fr))",
    gap: 12,
    overflowY: "auto" as const,
    alignContent: "start",
  } as const,
  photoThumb: {
    padding: 0,
    border: "none",
    background: "none",
    cursor: "pointer",
    display: "block",
    aspectRatio: "1",
    borderRadius: 8,
    overflow: "hidden" as const,
    backgroundColor: "#f1f5f9",
  } as const,
  modalOverlay: {
    position: "fixed" as const,
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    zIndex: 1100,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  } as const,
  modal: {
    background: "#fff",
    borderRadius: 12,
    padding: 24,
    minWidth: 320,
    maxWidth: "100%",
    boxShadow: "0 25px 50px -12px rgba(0,0,0,0.25)",
  } as const,
  modalTitle: { margin: "0 0 16px", fontSize: "1.125rem", fontWeight: 600, color: "#1e293b" } as const,
  modalActions: { display: "flex", gap: 12, marginTop: 20, justifyContent: "flex-end" } as const,
  input: {
    width: "100%",
    padding: "10px 12px",
    fontSize: "0.9375rem",
    borderRadius: 8,
    border: "1px solid #e2e8f0",
    boxSizing: "border-box" as const,
  } as const,
  select: {
    width: "100%",
    padding: "10px 12px",
    fontSize: "0.9375rem",
    borderRadius: 8,
    border: "1px solid #e2e8f0",
    backgroundColor: "#fff",
    marginTop: 8,
  } as const,
  dangerButton: {
    padding: "8px 16px",
    fontSize: "0.875rem",
    fontWeight: 500,
    borderRadius: 8,
    border: "none",
    background: "#dc2626",
    color: "#fff",
    cursor: "pointer",
  } as const,
};
