// Shared types, utils, and config. Add exports as needed.
export type {
  ActivitySnapshot,
  IndexActivitySlice,
  SyncActivitySlice,
  SyncPhase,
  SyncProgressMessage,
} from "./activity.js";
export type {
  AdminDbBackupItem,
  AdminDbBackupsResponse,
  AdminDbRestoreRequest,
  AdminDbRestoreResponse,
  ApiErrorBody,
  AuthConfigResponse,
  BackupConfigResponse,
  BackupRunStartedResponse,
  BackupSyncStatusResponse,
  CreatePersonResponse,
  DeletePersonResponse,
  FaceMatchAutoMerged,
  FaceMatchReviewItem,
  FaceMatchRunResponse,
  MediaListFields,
  MediaListItem,
  MediaListQueryResponse,
  MediaUploadResponse,
  MergePeopleResponse,
  PersonMediaPreviewItem,
  PersonSummary,
  SearchIndexStatusResponse,
  SearchMediaResponse,
  SearchResultItem,
  UpdatePersonResponse,
} from "./api.js";
